In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
import os
from matplotlib import pyplot as plt
from pprint import pprint
tool_dir = '/g/data/tm70/ml0072/COMMON/git_repos/fork_access-eval-recipes/ml_create_own_datastore'
sys.path.append(tool_dir)
from common_functions import _expt_name_combo, _read_ryaml, plot_time_series_combo, plot_time_series_combo2

yaml_input = 'Expts_manager_instan_short_test.yaml'
yamlfile_path = os.path.join(tool_dir,yaml_input)
yaml_input = _read_ryaml(yamlfile_path)
MOM_contrl_dir = yaml_input['base_dir_name']
contrl_name = 'DT_THERM_1800_DIABATIC_FIRST_True_THERMO_SPANS_COUPLING_False_DTBT_RESET_PERIOD_0'

MOM_expt_dir1 = yaml_input['namelists']['MOM_input']['MOM_expt_dir1']
MOM_list1_combo = yaml_input['namelists']['MOM_input']['MOM_list1_combo']
expt_names = _expt_name_combo(MOM_list1_combo)

MOM_dirs = [MOM_contrl_dir]+list(MOM_expt_dir1)
#MOM_dirs = list(MOM_expt_dir1)
pprint(MOM_dirs)
MOM_names = [contrl_name] + list(expt_names)
#MOM_names = list(expt_names)
pprint(MOM_names)

['Ctrl-1deg_jra55do_ryf',
 'expt0',
 'expt1',
 'expt2',
 'expt3',
 'expt4',
 'expt5',
 'expt6',
 'expt7',
 'expt8',
 'expt9',
 'expt10',
 'expt11',
 'expt12',
 'expt13',
 'expt14']
['DT_THERM_1800_DIABATIC_FIRST_True_THERMO_SPANS_COUPLING_False_DTBT_RESET_PERIOD_0',
 'DT_THERM_3600_DIABATIC_FIRST_True_THERMO_SPANS_COUPLING_False_DTBT_RESET_PERIOD_0',
 'DT_THERM_108000_DIABATIC_FIRST_False_THERMO_SPANS_COUPLING_True_DTBT_RESET_PERIOD_108000',
 'DT_THERM_108000_DIABATIC_FIRST_False_THERMO_SPANS_COUPLING_True_DTBT_RESET_PERIOD_0',
 'DT_THERM_90000_DIABATIC_FIRST_False_THERMO_SPANS_COUPLING_True_DTBT_RESET_PERIOD_90000',
 'DT_THERM_90000_DIABATIC_FIRST_False_THERMO_SPANS_COUPLING_True_DTBT_RESET_PERIOD_0',
 'DT_THERM_72000_DIABATIC_FIRST_False_THERMO_SPANS_COUPLING_True_DTBT_RESET_PERIOD_72000',
 'DT_THERM_72000_DIABATIC_FIRST_False_THERMO_SPANS_COUPLING_True_DTBT_RESET_PERIOD_0',
 'DT_THERM_54000_DIABATIC_FIRST_False_THERMO_SPANS_COUPLING_True_DTBT_RESET_PERIOD_54000',
 'DT_THERM_54000_DIABATIC_FIRST_False_THERMO_SPANS_COUPLING_True_DTBT_RESET_PERIOD_0',
 'DT_THERM_36000_DIABATIC_FIRST_False_THERMO_SPANS_COUPLING_True_DTBT_RESET_PERIOD_36000',
 'DT_THERM_36000_DIABATIC_FIRST_False_THERMO_SPANS_COUPLING_True_DTBT_RESET_PERIOD_0',
 'DT_THERM_18000_DIABATIC_FIRST_False_THERMO_SPANS_COUPLING_True_DTBT_RESET_PERIOD_18000',
 'DT_THERM_18000_DIABATIC_FIRST_False_THERMO_SPANS_COUPLING_True_DTBT_RESET_PERIOD_0',
 'DT_THERM_7200_DIABATIC_FIRST_False_THERMO_SPANS_COUPLING_True_DTBT_RESET_PERIOD_7200',
 'DT_THERM_7200_DIABATIC_FIRST_False_THERMO_SPANS_COUPLING_True_DTBT_RESET_PERIOD_0']

In [3]:
from intake import open_esm_datastore
output_expt_path = '/g/data/tm70/ml0072/COMMON/git_repos/Expts_manager/product_1_instan_short_runs/product1'
intake_esm_ds = 'intake_esm_ds.json'
datastore_tot = []
MOM_dirs_tot = []
MOM_names_tot = []
for i,j in zip(MOM_dirs,MOM_names):
    archive_path = os.path.join(f"{output_expt_path}",f"{i}","archive")
    datastore_path = os.path.join(f"{archive_path}",intake_esm_ds)
    if os.path.isfile(datastore_path):
        datastore = open_esm_datastore(datastore_path,columns_with_iterables=["variable"])
        datastore_tot.append(datastore)
        MOM_dirs_tot.append(f"{i}")
        MOM_names_tot.append(f"{j}")
MOM_dirs_tot
MOM_names_tot
datastore_tot

[<intake_esm_ds catalog with 2044 dataset(s) from 2632 asset(s)>,
 <intake_esm_ds catalog with 91 dataset(s) from 180 asset(s)>,
 <intake_esm_ds catalog with 91 dataset(s) from 180 asset(s)>,
 <intake_esm_ds catalog with 91 dataset(s) from 180 asset(s)>,
 <intake_esm_ds catalog with 91 dataset(s) from 180 asset(s)>,
 <intake_esm_ds catalog with 91 dataset(s) from 180 asset(s)>,
 <intake_esm_ds catalog with 91 dataset(s) from 180 asset(s)>,
 <intake_esm_ds catalog with 91 dataset(s) from 180 asset(s)>,
 <intake_esm_ds catalog with 91 dataset(s) from 180 asset(s)>,
 <intake_esm_ds catalog with 91 dataset(s) from 180 asset(s)>,
 <intake_esm_ds catalog with 91 dataset(s) from 180 asset(s)>,
 <intake_esm_ds catalog with 91 dataset(s) from 180 asset(s)>]

In [4]:
var = 'T_adx_2d'
datastore_tmp = datastore_tot[0]
cat_subset = datastore_tmp.search(
    variable=[var]
)
dsets2 = cat_subset.df
dsets2

,path,realm,variable,frequency,start_date,end_date,variable_long_name,variable_standard_name,variable_cell_methods,variable_units,filename,file_id
0,/g/data/tm70/ml0072/COMMON/git_repos/Expts_man...,ocean,"[T_adx_2d, average_T1, average_T2, average_DT,...",1mon,"1900-01-01, 00:00:00","1901-01-01, 00:00:00",['Vertically Integrated Advective Zonal Flux o...,"['', '', '', '', '']","['yh:sum xq:point time: mean', '', '', '', '']","['W', 'days since 1900-01-01 00:00:00', 'days ...",access-om3.mom6.2d.T_adx_2d.1mon.mean._1900.nc,access_om3_mom6_2d_T_adx_2d_1mon_mean_1900
1,/g/data/tm70/ml0072/COMMON/git_repos/Expts_man...,ocean,"[T_adx_2d, average_T1, average_T2, average_DT,...",1mon,"1901-01-01, 00:00:00","1902-01-01, 00:00:00",['Vertically Integrated Advective Zonal Flux o...,"['', '', '', '', '']","['yh:sum xq:point time: mean', '', '', '', '']","['W', 'days since 1900-01-01 00:00:00', 'days ...",access-om3.mom6.2d.T_adx_2d.1mon.mean._1901.nc,access_om3_mom6_2d_T_adx_2d_1mon_mean_1901
2,/g/data/tm70/ml0072/COMMON/git_repos/Expts_man...,ocean,"[T_adx_2d, average_T1, average_T2, average_DT,...",1mon,"1902-01-01, 00:00:00","1903-01-01, 00:00:00",['Vertically Integrated Advective Zonal Flux o...,"['', '', '', '', '']","['yh:sum xq:point time: mean', '', '', '', '']","['W', 'days since 1900-01-01 00:00:00', 'days ...",access-om3.mom6.2d.T_adx_2d.1mon.mean._1902.nc,access_om3_mom6_2d_T_adx_2d_1mon_mean_1902
3,/g/data/tm70/ml0072/COMMON/git_repos/Expts_man...,ocean,"[T_adx_2d, average_T1, average_T2, average_DT,...",1mon,"1903-01-01, 00:00:00","1904-01-01, 00:00:00",['Vertically Integrated Advective Zonal Flux o...,"['', '', '', '', '']","['yh:sum xq:point time: mean', '', '', '', '']","['W', 'days since 1900-01-01 00:00:00', 'days ...",access-om3.mom6.2d.T_adx_2d.1mon.mean._1903.nc,access_om3_mom6_2d_T_adx_2d_1mon_mean_1903
4,/g/data/tm70/ml0072/COMMON/git_repos/Expts_man...,ocean,"[T_adx_2d, average_T1, average_T2, average_DT,...",1mon,"1904-01-01, 00:00:00","1905-01-01, 00:00:00",['Vertically Integrated Advective Zonal Flux o...,"['', '', '', '', '']","['yh:sum xq:point time: mean', '', '', '', '']","['W', 'days since 1900-01-01 00:00:00', 'days ...",access-om3.mom6.2d.T_adx_2d.1mon.mean._1904.nc,access_om3_mom6_2d_T_adx_2d_1mon_mean_1904
5,/g/data/tm70/ml0072/COMMON/git_repos/Expts_man...,ocean,"[T_adx_2d, average_T1, average_T2, average_DT,...",1mon,"1905-01-01, 00:00:00","1906-01-01, 00:00:00",['Vertically Integrated Advective Zonal Flux o...,"['', '', '', '', '']","['yh:sum xq:point time: mean', '', '', '', '']","['W', 'days since 1900-01-01 00:00:00', 'days ...",access-om3.mom6.2d.T_adx_2d.1mon.mean._1905.nc,access_om3_mom6_2d_T_adx_2d_1mon_mean_1905
6,/g/data/tm70/ml0072/COMMON/git_repos/Expts_man...,ocean,"[T_adx_2d, average_T1, average_T2, average_DT,...",1mon,"1906-01-01, 00:00:00","1907-01-01, 00:00:00",['Vertically Integrated Advective Zonal Flux o...,"['', '', '', '', '']","['yh:sum xq:point time: mean', '', '', '', '']","['W', 'days since 1900-01-01 00:00:00', 'days ...",access-om3.mom6.2d.T_adx_2d.1mon.mean._1906.nc,access_om3_mom6_2d_T_adx_2d_1mon_mean_1906
7,/g/data/tm70/ml0072/COMMON/git_repos/Expts_man...,ocean,"[T_adx_2d, average_T1, average_T2, average_DT,...",1mon,"1907-01-01, 00:00:00","1908-01-01, 00:00:00",['Vertically Integrated Advective Zonal Flux o...,"['', '', '', '', '']","['yh:sum xq:point time: mean', '', '', '', '']","['W', 'days since 1900-01-01 00:00:00', 'days ...",access-om3.mom6.2d.T_adx_2d.1mon.mean._1907.nc,access_om3_mom6_2d_T_adx_2d_1mon_mean_1907
8,/g/data/tm70/ml0072/COMMON/git_repos/Expts_man...,ocean,"[T_adx_2d, average_T1, average_T2, average_DT,...",1mon,"1908-01-01, 00:00:00","1909-01-01, 00:00:00",['Vertically Integrated Advective Zonal Flux o...,"['', '', '', '', '']","['yh:sum xq:point time: mean', '', '', '', '']","['W', 'days since 1900-01-01 00:00:00', 'days ...",access-om3.mom6.2d.T_adx_2d.1mon.mean._1908.nc,access_om3_mom6_2d_T_adx_2d_1mon_mean_1908
9,/g/data/tm70/ml0072/COMMON/git_repos/Expts_man...,ocean,"[T_adx_2d, average_T1, average_T2, average_DT,...",1mon,"1909-01-01, 00:00:00","1910-01-01, 00:00:00",['Vertically Integrated Advective Zonal Flux o...,"['', '', '', '', '']","['yh:sum xq:point time: mean', '', '', '', '']","['W', 'days since 1900-01-01 00:00:00', 'days ...",access-om3.mom6.2d.T_adx_2d.1mon.mean._1909.nc,access_om3_mom6_2d_T_adx_2d_1mon_mean_1909
10,/g/data/tm70/ml0072/COMMON/git_repos/Expts_man...,ocean,"[T_adx_2d, average_T1, average_T2, average_DT,...",1mon,"1910-01-01, 00:00:00","1911-01-01, 00:00:00",['Vertically Integrated Advective Zonal Flux o...,"['', '', '', '', '']","['yh:sum xq:point time: mean', '', '', '', '']","['W', 'days since 1900-01-01 00:00:00', 'days ...",access-om3.mom6.2d.T_adx_2d.1mon.mean._1910.nc,access_om3_mom6_2d_T_adx_2d_1mon_mean_1910
11,/g/data/tm70/ml0072/COMMON/git_repos/Expts_man...,ocean,"[T_adx_2d, average_T1, average_T2, average_DT,...",1mon,"1911-01-01, 00:00:00","1912-01-01, 00:00:00",['Vertically Integrated Advective Zonal Flux o...,"['', '', '', '', '']","['yh:sum xq:point time: mean', '', '', '', '']","['W', 'days since 1900-01-01 00:00:00', 'days ...",access-om3.mom6.2d.T_adx_2d.1mon.mean._1911.nc,access_om3_mom6_2d_T_adx_2d_1mon_mean_1911
12,/g/data/tm70/ml0072/COMMON/git_repos/Expts_man...,ocean,"[T_adx_2d, average_T1, average_T2, average_DT,...",1mon,"1912-01-01, 00:00:00","1913-01-01, 00:00:00",['Vertically Integrated Advective Zonal Flux o...,"['', '', '', '', '']","['yh:sum xq:point time: mean', '', '', '', '']","['W', 'days since 1900-01-01 00:00:00', 'days ...",access-om3.mom6.2d.T_adx_2d.1mon.mean._1912.nc,access_om3_mom6_2d_T_adx_2d_1mon_mean_1912
13,/g/data/tm70/ml0072/COMMON/git_repos/Expts_man...,ocean,"[T_adx_2d, average_T1, average_T2, average_DT,...",1mon,"1913-01-01, 00:00:00","1914-01-01, 00:00:00",['Vertically Integrated Advective Zonal Flux o...,"['', '', '', '', '']","['yh:sum xq:point time: mean', '', '', '', '']","['W', 'days since 1900-01-01 00:00:00', 'days ...",access-om3.mom6.2d.T_adx_2d.1mon.mean._1913.nc,access_om3_mom6_2d_T_adx_2d_1mon_mean_1913
14,/g/data/tm70/ml0072/COMMON/git_repos/Expts_man...,ocean,"[T_adx_2d, average_T1, average_T2, average_DT,...",1mon,"1914-01-01, 00:00:00","1915-01-01, 00:00:00",['Vertically Integrated Advective Zonal Flux o...,"['', '', '', '', '']","['yh:sum xq:point time: mean', '', '', '', '']","['W', 'days since 1900-01-01 00:00:00', 'days ...",access-om3.mom6.2d.T_adx_2d.1mon.mean._1914.nc,access_om3_mom6_2d_T_adx_2d_1mon_mean_1914
15,/g/data/tm70/ml0072/COMMON/git_repos/Expts_man...,ocean,"[T_adx_2d, average_T1, average_T2, average_DT,...",1mon,"1915-01-01, 00:00:00","1916-01-01, 00:00:00",['Vertically Integrated Advective Zonal Flux o...,"['', '', '', '', '']","['yh:sum xq:point time: mean', '', '', '', '']","['W', 'days since 1900-01-01 00:00:00', 'days ...",access-om3.mom6.2d.T_adx_2d.1mon.mean._1915.nc,access_om3_mom6_2d_T_adx_2d_1mon_mean_1915
16,/g/data/tm70/ml0072/COMMON/git_repos/Expts_man...,ocean,"[T_adx_2d, average_T1, average_T2, average_DT,...",1mon,"1916-01-01, 00:00:00","1917-01-01, 00:00:00",['Vertically Integrated Advective Zonal Flux o...,"['', '', '', '', '']","['yh:sum xq:point time: mean', '', '', '', '']","['W', 'days since 1900-01-01 00:00:00', 'days ...",access-om3.mom6.2d.T_adx_2d.1mon.mean._1916.nc,access_om3_mom6_2d_T_adx_2d_1mon_mean_1916
17,/g/data/tm70/ml0072/COMMON/git_repos/Expts_man...,ocean,"[T_adx_2d, average_T1, average_T2, average_DT,...",1mon,"1917-01-01, 00:00:00","1918-01-01, 00:00:00",['Vertically Integrated Advective Zonal Flux o...,"['', '', '', '', '']","['yh:sum xq:point time: mean', '', '', '', '']","['W', 'days since 1900-01-01 00:00:00', 'days ...",access-om3.mom6.2d.T_adx_2d.1mon.mean._1917.nc,access_om3_mom6_2d_T_adx_2d_1mon_mean_1917
18,/g/data/tm70/ml0072/COMMON/git_repos/Expts_man...,ocean,"[T_adx_2d, average_T1, average_T2, average_DT,...",1mon,"1918-01-01, 00:00:00","1919-01-01, 00:00:00",['Vertically Integrated Advective Zonal Flux o...,"['', '', '', '', '']","['yh:sum xq:point time: mean', '', '', '', '']","['W', 'days since 1900-01-01 00:00:00', 'days ...",access-om3.mom6.2d.T_adx_2d.1mon.mean._1918.nc,access_om3_mom6_2d_T_adx_2d_1mon_mean_1918
19,/g/data/tm70/ml0072/COMMON/git_repos/Expts_man...,ocean,"[T_adx_2d, average_T1, average_T2, average_DT,...",1mon,"1919-01-01, 00:00:00","1920-01-01, 00:00:00",['Vertically Integrated Advective Zonal Flux o...,"['', '', '', '', '']","['yh:sum xq:point time: mean', '', '', '', '']","['W', 'days since 1900-01-01 00:00:00', 'days ...",access-om3.mom6.2d.T_adx_2d.1mon.mean._1919.nc,access_om3_mom6_2d_T_adx_2d_1mon_mean_1919